### ISSUE TITLE
Deprecation warning on 'include'

### ISSUE THREAD

**Issue by celestian** [freeipa/freeipa-pr-ci#119]
I caught deprecation warning:
```
$ ansible-playbook -i ansible/inventory ansible/prepare_devel_test_runners.yml
[DEPRECATION WARNING]: The use of 'include' for tasks has been deprecated. Use 'import_tasks' for static inclusions or 'include_tasks' for dynamic inclusions. This feature will be removed in a future release. 
Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: include is kept for backwards compatibility but usage is discouraged. The module documentation details page may explain more about this rationale.. This feature will be removed in a 
future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
Owner of monitored GitHub repo:
```

**Comment by tomaskrizek** [comment]
It seems like simple replacement in all playbooks/roles would do it. We just need to make sure it's compatible with the lowest supported version of ansible (currently >= 2.3).

**Comment by tomaskrizek** [comment]
The new `import_tasks` is only supported in 2.4+.

Since `include` is going to be supported until 2.8, I'd say we keep it this way for backwards compatibility with 2.3 and deal with it in the future.

**Comment by netoarmando** [comment]
Deprecation warning aren't displayed any more. However, Ansible documantion [states](https://docs.ansible.com/ansible/latest/modules/include_module.html#notes) the following not about `include` module:
> This module will still be supported for some time but we are looking at deprecating it in the near future.
