### ISSUE TITLE
Run the new job for all PRs once it gets added

### ISSUE THREAD

**Issue by stlaz** [freeipa/freeipa-pr-ci#125]
As all jobs are being run on a new version of a template (e.g. when we did F25->F26 move), a new job (like the external CA added recently) should probably be run once added for all PRs, too, so that we know that no new PR breaks it.

**Comment by tomaskrizek** [comment]
To work around this problem, you can add `re-run` label to generate the new test in the PR without the need to rebase.

**Comment by f-trivino** [comment]
We believe that adding re-run label is enough to fix this issue.
