### ISSUE TITLE
Migrate Python test suites from Travis CI to PR CI

### ISSUE THREAD

**Issue by tomaskrizek** [freeipa/freeipa-pr-ci#146]
Travis CI is currently overloaded, because it executes the following tests:

- build, lint
- Python2 unit tests
- Python3 unit tests
- tox tests
- web unit tests (soon)

It'd make sense to move the Python2&3 tests to PR CI, because they take quite a bit of time (~1h30m per PR in Travis CI) and it currently makes Travis a bottleneck, because we're using the free version.

**Comment by tomaskrizek** [comment]
Python 2&3 tests are currently broken in Travis, because of an update to Travis and missing IPv6 loopback.

I think the following would have to be done:
1. create a new vagrantfile for unit testing with single VM
2. create a provisioning role that will install freeipa, create needed config files (similar to [`install_server`](https://github.com/freeipa/freeipa/blob/master/.test_runner_config.yaml#L50) and [`prepare_tests`](https://github.com/freeipa/freeipa/blob/master/.test_runner_config.yaml#L61) roles from travis config)
3. create `RunPytest2` and `RunPytest3` to distinguish between jobs executed with `ipa-run-tests-2` and `ipa-run-tests-3`
4. add option to execute additional commands after the tests (e.g. searching httpd error log for `BytesWarning`)
5. add new jobs to [`.freeipa-pr-ci.yaml`](https://github.com/freeipa/freeipa/blob/master/.freeipa-pr-ci.yaml) and define less resource-consuming topology
6. assign lower range of priorities to single-machine jobs to avoid them being taken by large runners; spawn additional smaller runners instead of bigger ones in OpenStack

Steps 1-2 are a bit similar to what's being done for webui testing (PR #149).

**Comment by tomaskrizek** [comment]
I addressed steps 1-3 as a part of #149

**Comment by netoarmando** [comment]
Those tests are being executed by Azure as well since https://github.com/freeipa/freeipa/pull/3137.

We still need to determinate whether or not we want to move tests to PR-CI.
