### ISSUE TITLE
Green mark for skipped tests in PR CI is confusing.

### ISSUE THREAD

**Issue by gkaihorodova** [freeipa/freeipa-pr-ci#163]
When tests skipped it reflects in html.report, but green mark for runs looks a bit confusing.
I think, not everyone will actually check all logs and reports and green mark would be a green light that all good. It needs improvement.

**Comment by pvoborni** [comment]
Definity agree that if all tests are skipped then there is something fishy which needs to be improved. 

On the other hand, sometimes skipping a test is a valid thing. So here, it would make sense to check what are the "unwanted" skips and the "ok" skips. 

E.g. a problematic skip, IMO, is: 

```
('/usr/lib/python3.6/site-packages/pytest_multihost/plugin.py', 107, "Skipped: Not enough resources configured: Domain 0 not configured: {'type': 'IPA', 'hosts': {'master': 1, 'replica': 0, 'client': 1}}")
```
E.g. in https://fedorapeople.org/groups/freeipa/prci/jobs/13d407ea-20da-11e8-b34e-fa163ee5d6a5/report.html

That IMO should be a fail or when PR-CI supports different sizes of runners then this task should not be taken by the runner.

Or, could the problem be that the task has not valid topology defined?

**Comment by slaykovsky** [comment]
> Or, could the problem be that the task has not valid topology defined
This.

**Comment by f-trivino** [comment]
A valid topology should be used for running the test suite. This is not a bug.
