### ISSUE TITLE
Fail in case of a SELinux denial

### ISSUE THREAD

**Issue by stlaz** [freeipa/freeipa-pr-ci#203]
Currently, the VM machines are running in permissive SELinux context. That's more or less fine, but the test should fail if there are SELinux denials, which does not happen now.

**Comment by tomaskrizek** [comment]
I think it'd be better to have a separate tests that would check for selinux denials (for all tests combined). That way it's easier to tell whether there's a SELinux policy issue or an issue with the test itself.

**Comment by stlaz** [comment]
I do not really care about the implementation, but I would like to at least see a failure for SELinux denials. It could just as well be collected in a separate, grouped target.

**Comment by fcami** [comment]
@stlaz I actually don't think it is wise:
- we often see AVCs related to other components in Fedora. That comes and goes.
- sometimes an AVC should be silenced (dontaudit) as it is really harmless.
The actual solution to the above problem is to have nightlies with SELinux in Enforcing mode or the possibility to switch a test to Enforcing using the PR-CI template. We have both now.
@netoarmando I think we can close this. @stlaz please feel free to reopen if your concern is not addressed.

**Comment by fcami** [comment]
@netoarmando I think this can be closed since we have separate nightly runs with SELinux in Enforcing mode. Do you agree?

**Comment by netoarmando** [comment]
I agree! Thanks!
