### ISSUE TITLE
freeipa-pr-ci does not support symlinks in FreeIPA repository

### ISSUE THREAD

**Issue by pvomacka** [freeipa/freeipa-pr-ci#22]
When we add symlinks into FreeIPA repository the freeipa-pr-ci fails during creating tarball. 

Error from log: 

> Error when writing tar.gz archive at /root/rpmbuild/SOURCES/freeipa-4.5.90test.tar.gz: [Errno 2] No such file or directory: '/tmp/freeipa-4.5.90test/install/ui/js/plugins'
> 2017-07-31 11:42:39,764    DEBUG  	to retry, use: --limit @/root/freeipa-pr-ci/ansible/build.retry

Link to the log with error: [runner.log.gz](https://fedorapeople.org/groups/freeipa/prci/jobs/7121ffb2-75d4-11e7-aa19-001a4a23162d/runner.log.gz)

**Comment by tomaskrizek** [comment]
Symlinks are ok. This error is encountered when the link points to a non-existent location. I think the proper solution is to not have broken symlinks in the repo. However, the build procedure could be adjusted to allow broken symlinks to be part of the tarball.

**Comment by tomaskrizek** [comment]
Removed the broken symlink, works now.
