### ISSUE TITLE
VM's are not destroyed in any exit code

### ISSUE THREAD

**Issue by dhnunes** [freeipa/freeipa-pr-ci#239]
When prci stops for any reason external to a task failure ( Keyboard Interrupt, abrupt process kill, or any system error ), prci must kill vms before leave ( if possible ) and check if there is any vm running before start to check the tasks.

In a situation where a task consumes a lot of resources and process fails and keeps the vms online, the next start will not be able to run anything due to "Not available resources".

**Comment by f-trivino** [comment]
We have decided to call vagrant destroy when prci fails or the execution is interrupted.

**Comment by dhnunes** [comment]
Force pushed, improved commit title and message.

**Comment by netoarmando** [comment]
After https://github.com/freeipa/freeipa-pr-ci/pull/319 PR-CI is destroying VMs after running all jobs. That is good enough to handle these scenarios.
