### ISSUE TITLE
Name is already taken when create new template

### ISSUE THREAD

**Issue by dhnunes** [freeipa/freeipa-pr-ci#247]
During the creation of a new rawhide template, if it fail for some reason and you let to solve in next day ( just as example ), when we ran the script create_template_box, the box prepare step of role returns this error:

```
TASK [box/prepare : bring the image online] ********************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "vagrant up", "delta": "0:00:04.582788", "end": "2019-01-17 11:18:47.765562", "msg": "non-zero return code", "rc": 1, "start": "2019-01-17 11:18:43.182774", "stderr": "Name `ci-master-frawhide_template` of domain about to create is already taken. Please try to run\n`vagrant up` command again.", "stderr_lines": ["Name `ci-master-frawhide_template` of domain about to create is already taken. Please try to run", "`vagrant up` command again."], "stdout": "==> vagrant: A new version of Vagrant is available: 2.2.3!\n==> vagrant: To upgrade visit: https://www.vagrantup.com/downloads.html\n\nBringing machine 'template' up with 'libvirt' provider...", "stdout_lines": ["==> vagrant: A new version of Vagrant is available: 2.2.3!", "==> vagrant: To upgrade visit: https://www.vagrantup.com/downloads.html", "", "Bringing machine 'template' up with 'libvirt' provider..."]}
	to retry, use: --limit @[...]/ansible/create_template_box.retry
```
This is happening because the vm is already created in local kvm server but is off, for this reason, the playbook is not able to understand this and delete this vm.

The manual work arround now is delete the vm manually and re-run the script.

**Comment by netoarmando** [comment]
It happened because you have restarted your computer before the [end of the playbook](https://github.com/freeipa/freeipa-pr-ci/blob/df265cb9f6930eeb1d8a3237bf9c7a92e36fefdc/ansible/roles/box/package/tasks/main.yml#L39-L43).

PR-CI uses `/tmp` to create the template box, which is wiped when you restart.

Closing this as 'wont' fix' for now.
