### ISSUE TITLE
Tests not triggered when last commit doesn't change after force-pushing

### ISSUE THREAD

**Issue by netoarmando** [freeipa/freeipa-pr-ci#258]
Comment made to a pull request that didn't trigger PR-CI:

> it seems PRCI is disturbed by a force-push if the last commit did not change (I added a new before-last commit and the last commit hash did not change, it's probably why PRCI wasn't re-triggered).

-- https://github.com/freeipa/freeipa/pull/2859#issuecomment-471064116

**Comment by fcami** [comment]
FWIW I also noticed that while working on https://github.com/freeipa/freeipa/pull/2888

**Comment by f-trivino** [comment]
I think this is happening here: https://github.com/freeipa/freeipa/pull/3061

**Comment by f-trivino** [comment]
This is a duplicated ticket from https://github.com/freeipa/freeipa-pr-ci/issues/264 . I close this one.
