### ISSUE TITLE
Allow runner deployment and development without github 

### ISSUE THREAD

**Issue by tomaskrizek** [freeipa/freeipa-pr-ci#26]
1. Modify runner deployment playbook to allow deployment of runner without github communication.
2. Provide steps / script to deploy runner without github part.
3. Update build / run-pytest scripts to enable local builds and test runs.

**Comment by f-trivino** [comment]
We believe that this feature is not adding significant value and requires significant effort to implement it since it implies one of the main pr-ci design aspects to be modified. We close this ticket for now.
