### ISSUE TITLE
Runner disk cleanup

### ISSUE THREAD

**Issue by tomaskrizek** [freeipa/freeipa-pr-ci#27]
Once a new template is generated and uploaded to vagrantcloud, there should be a (default) option to also revoke and older version from vagrant cloud and to delete it from all the runners via ansible. 

Two versions per template should be kept. One current stable and one updated one.

**Comment by felipevolpone** [comment]
I think we could go with a script that runs after the upload script and ssh into the machines and removes the old boxes. What do you think? 
My concern is how to know every runner deployment we have.

**Comment by tomaskrizek** [comment]
We need to solve 2 issues:

- revoking the old box -- we shouldn't need more than 2 active boxes (1 stable, 1 updated or deprecated). We should be very careful not to revoke a stable box. E.g. there is stable 9.0.1 and old 9.0.0. When we upload 9.0.2, we can delete 9.0.0. But then we find out we need more changes, so we create another update, 9.0.3. In this case, we *can't* remove the 9.0.1, but we should instead revoke 9.0.2.

- removing the old box from runners -- I don' think there's an ideal solution. I think we should just keep ansible inventory up to date and perhaps prompt the user to update it before confirming to proceed with the deletion of boxes.
