### ISSUE TITLE
vargant up -- RunTimeError: can't modify frozen String

### ISSUE THREAD

**Issue by dhnunes** [freeipa/freeipa-pr-ci#275]
When PR-CI starts to bring Vagrant Environment UP, we were facing the error in $TITLE.

This error is regarding to the last line presented in Vagrantfiles:

``` Vagrant::DEFAULT_SERVER_URL.replace("https://vagrantcloud.com") ```

This is the error generated:

``` bash
[root@reproducer-3130 eb7cad3e-82ed-11e9-88cc-001c42026ead]# vagrant up --no-provision --parallel
There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
a syntax error.

Path: /root/freeipa-pr-ci/jobs/eb7cad3e-82ed-11e9-88cc-001c42026ead/Vagrantfile
Line number: 0
Message: FrozenError: can't modify frozen String
```

After removing the given line, the vagrant proceeds without problems.

Some refer to this problem: https://github.com/p4lang/tutorials/issues/131

**Comment by netoarmando** [comment]
We need to fix it to support newer releases of Vagrant.
The one included in Fedora 28 repo is okay, but Fedora 29's complains about that line.

**Comment by netoarmando** [comment]
Done: https://github.com/freeipa/freeipa-pr-ci/commit/74fcc3ec9811d68689d849aa32c101e070621b79
