### ISSUE TITLE
Test fails with vagrant error -15 and does not publish report

### ISSUE THREAD

**Issue by flo-renaud** [freeipa/freeipa-pr-ci#345]
Sometimes a PR-CI test fails with the following error message and does not publish its report:
```
2020-02-02 11:39:02,087    DEBUG  Process "vagrant ssh -c IPATEST_YAML_CONFIG=/vagrant/ipa-test-config.yaml ipa-run-tests test_integration/test_external_ca.py::TestExternalCAInvalidCert test_integration/test_external_ca.py::TestExternalCAInvalidIntermediate --verbose --logging-level=debug --logfile-dir=/vagrant/ --html=/vagrant/report.html --junit-xml=/vagrant/junit.xml" exited with error code -15
Traceback (most recent call last):
  File "/root/freeipa-pr-ci/tasks/common.py", line 124, in __call__
    super(FallibleTask, self).__call__()
  File "/root/freeipa-pr-ci/tasks/common.py", line 111, in __call__
    raise self.exc
  File "/root/freeipa-pr-ci/tasks/common.py", line 94, in __target
    self._run()
  File "/root/freeipa-pr-ci/tasks/common.py", line 161, in _run
    raise PopenException(self)
tasks.common.PopenException: Process "vagrant ssh -c IPATEST_YAML_CONFIG=/vagrant/ipa-test-config.yaml ipa-run-tests test_integration/test_external_ca.py::TestExternalCAInvalidCert test_integration/test_external_ca.py::TestExternalCAInvalidIntermediate --verbose --logging-level=debug --logfile-dir=/vagrant/ --html=/vagrant/report.html --junit-xml=/vagrant/junit.xml" exited with error code -15
2020-02-02 11:39:02,089    ERROR  >>>>>> PYTEST ERROR (-15) <<<<<<
```

Example: PR [41881](https://github.com/freeipa/freeipa/pull/4188) with the following [logs](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/0940ae1c-45b0-11ea-84af-fa163e968362/runner.log.gz).

**Comment by netoarmando** [comment]
@flo-renaud, just to confirm, was that the first time you saw that happening in a test outside rawhide?

**Comment by flo-renaud** [comment]
@netoarmando 
The issue also happened on PR 4166: [testing_master_previous](https://github.com/freeipa/freeipa/pull/4166 )

**Comment by netoarmando** [comment]
I found one possible reason for this.

I had to restart all runners while they were running tests, I looked into 27 logs and found that error at 25 of them, all within the period I was restarting the runners.

Something was restarting the runners, possibly the `autocleaner.py` or our external checker.

**Comment by netoarmando** [comment]
We were running a job that was restarting all runners every day at 5:00 UTC, all errors happened about that time.

I have disabled that job, closing this for now.

**Comment by flo-renaud** [comment]
Issue occurred in PR [4590](https://github.com/freeipa/freeipa/pull/4590) for the test `dns_locations`: [logs](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/21d46c2c-878f-11ea-8dbf-fa163e53827b/)

**Comment by netoarmando** [comment]
> Issue occurred in PR [4590](https://github.com/freeipa/freeipa/pull/4590) for the test `dns_locations`: [logs](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/21d46c2c-878f-11ea-8dbf-fa163e53827b/)

This happened to `big-runner-4` for some reason other than a periodic reboot, uptime of that host is about 22 days, `prci` is running since then.

**Comment by flo-renaud** [comment]
Also happened in PR #232 on 8 tests

**Comment by netoarmando** [comment]
Closing this, since it hasn't been observed in the last 2 months.
SIGTERM can still happen during maintenance in PR-CI runners. I'll leave a message if that was done on purpose during a nightly run.
