### ISSUE TITLE
human_log.py: undefined name reload()

### ISSUE THREAD

**Issue by tiran** [freeipa/freeipa-pr-ci#354]
The callback plugin ``human_log.py`` is not compatible with Python 3 and fails to load:

```
[WARNING]: Skipping plugin (/root/freeipa-pr-ci/ansible/callback_plugins/human_log.py) as it seems to be invalid: name 'reload' is not defined
```

The ``reload`` builtin was removed from Python in 3.0.

**Comment by netoarmando** [comment]
https://github.com/freeipa/freeipa-pr-ci/pull/387 is fixing this.

**Comment by netoarmando** [comment]
PR #387 deployed to all runners.
