### ISSUE TITLE
Need to increase RAM on Vagrant images

### ISSUE THREAD

**Issue by flo-renaud** [freeipa/freeipa-pr-ci#393]
The upstream test `fedora-latest/mask` is failing because of a new check added in commit [cfad7a](https://pagure.io/freeipa/c/cfad7af35dd5a2cdd4081d1e9ac7c245f47f1dce?branch=master) to `ipa-server-install`. From now on, the utility requires at least 1.6GB of usable RAM to install the server. See PR #[407](https://github.com/freeipa-pr-ci2/freeipa/pull/407) with the following [report](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/809ee750-f6ed-11ea-ab45-fa163ee0e2d4/report.html) and logs:
```
Less than the minimum 1.6GB of RAM is available, 1.24GB available
The ipa-server-install command failed. See /var/log/ipaserver-install.log for more information
```

The Vagrant images need to be modified to have more memory. The current setttings define `domain.memory = 2400` (see https://github.com/freeipa/freeipa-pr-ci/blob/master/templates/vagrantfiles/Vagrantfile.ipaserver). Note that the tests using other templates with `domain.memory = 2750` seem to work well.

**Comment by netoarmando** [comment]
PR https://github.com/freeipa/freeipa-pr-ci/pull/394 deployed to all runners.
