### ISSUE TITLE
tox testing

### ISSUE THREAD

**Issue by tomaskrizek** [freeipa/freeipa-pr-ci#42]
Add support for running tox tests in PR CI.

**Comment by tomaskrizek** [comment]
Raising a priority on this, because we've released a broken PyPI package and this would have prevented it.

**Comment by felipevolpone** [comment]
PR #103 address this.

**Comment by tomaskrizek** [comment]
Tox tests were added to travis CI in https://github.com/freeipa/freeipa/pull/1293 . I'll keep this open in case we want to use PR CI resources for this test, but I'm lowering the priority to unknown.

**Comment by netoarmando** [comment]
Tox tests are being executed by Azure as well since https://github.com/freeipa/freeipa/pull/3137.
