### ISSUE TITLE
runner deployment: extra configuration

### ISSUE THREAD

**Issue by tomaskrizek** [freeipa/freeipa-pr-ci#67]
The template was tested with Fedora Cloud Base template and works out of the box for this distro. However, if additional features are turned on, they need to be configured.

- If firewall is configured on the runner machine, enable the required services (e.g. NFS).
- Enable NAT routing for nested VMs.

**Comment by tomaskrizek** [comment]
@abbra I've documented the issues you've hit when deploying the PR CI. However, since the playbook works out of the box for the machines we're using, I think this is a rather low-priority fix.

**Comment by f-trivino** [comment]
For the time being we have no plans to use a different distro than fedora, so this ticket is not applicable. We close this ticket.
