### ISSUE TITLE
runner monitoring

### ISSUE THREAD

**Issue by tomaskrizek** [freeipa/freeipa-pr-ci#69]
Currently, there is no good way to monitor status and health of the individual runners. A monitoring solution using for example [zabbix](https://www.zabbix.com/) would be ideal, so we can track the activity and state of production runners.

**Comment by felipevolpone** [comment]
We have a Zabbix instance configured. Still needs to be done:

- Expand it to all VMs
- Parse systemctl status prci
- Create a graph with the data
- Change playbook to install zabbix-agent and change the conf file

**Comment by tomaskrizek** [comment]
In the future, I think it'd also be good to implement additional checks, such as:
- remaining disk space (perhaps zabbix does this one already)
- number of ERRORs in prci log
- number of WARNINGs in prci log
- last X entries from prci log

**Comment by tomaskrizek** [comment]
I think all the zabbix configuration should be done in an automated way. That way we can write an ansible role for it and quickly create a new instance in case we lose the old one. It might be easier and quicker to configure it through web interface, but I believe automation will pay off in the long run.

**Comment by tomaskrizek** [comment]
I think this may take some time to implement in a proper and fully automated way, so I'm dropping the priority on this in favor of more pressing issues.

**Comment by felipevolpone** [comment]
Yes, in order to have it fully automated we also need:
- [ ] Configure Zabbix to discover zabbix agents automatically

**Comment by f-trivino** [comment]
We plan to add new view in PR-CI dashboard to report general status of all runners.

**Comment by f-trivino** [comment]
after implementing auto-recovery and auto-rescue automation I believe this is not needed, so I closed this ticket.
