### ISSUE TITLE
artifacts: failover remote storage

### ISSUE THREAD

**Issue by tomaskrizek** [freeipa/freeipa-pr-ci#71]
If fedorapeople.org goes down or is slow, we're unable to publish build and test artifacts, which effectively disables our CI. A failover mechanism should be implemented that could be used in such cases. It should use an alternative server for publishing. It only has to follow the same directory structure, but it can have more limited lifetime of data and features (i.e. no in-browser support for `*.gz` files).

**Comment by f-trivino** [comment]
This ticket is not applicable since we use AWS to publish results.
