### ISSUE TITLE
py.test: log output of called subprocesses

### ISSUE THREAD

**Issue by tomaskrizek** [freeipa/freeipa-pr-ci#76]
The `runner.log` is missing the output of commands like `ipa-server-install`, which makes debugging some issues much harder or impossible. Output of subcommands that are called by py.test should be logged either directly in the `runner.log` or in a separate file.

**Comment by tomaskrizek** [comment]
Perhaps this will have to be fixed in FreeIPA, since it seems to work in `ipa-4-5` branch.

**Comment by davidkupka** [comment]
Do you really need the output? I understand it's convenient but everything you need is in `/var/log/ipaserver-install.log` which is collected and provided.

**Comment by tomaskrizek** [comment]
Unfortunately, `/var/log/ipaserver-install.log` isn't collected every time. For example, the `external_ca` test failed to install IPA server on master and the log wasn't collected: https://fedorapeople.org/groups/freeipa/prci/jobs/8df9ad3e-8e51-11e7-8ed4-fa163e723304/ 

However, this may be an issue with the test itself. In that case we could just fix the test and close this issue.

**Comment by tomaskrizek** [comment]
The missing log was an issue with the test itself. The lack of output from py.test isn't that significant, because the log should be available. In any case, if this is to be fixed/improved, it should be done in FreeIPA.

**Comment by tomaskrizek** [comment]
This issue also happens when when a server installation times out, which has been happening quite frequently as of late. Since the process is killed, py.test won't collect any logs. Without any output or logs from the executed commands, it's quite impossible to debug the issue, unless there's a live reproducer.

Perhaps this should be fixed on IPA side, but we could also make sure to somehow collect logs in case of a timeout. In either case, I'm reopening the issue so we can track the progress.

**Comment by felipevolpone** [comment]
PR github.com/freeipa/freeipa/pull/1234 address this issue.
